// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"three","status":true,"description":"","parameters":{}},
{"name":"Mintyy_ThreeCorePlugin","status":true,"description":"A core plugin to deal with all 3D related plugins by Mintyy.","parameters":{"-- PARALLAX --":"","Parallax Style":"Skybox","-- BATTLEBACK --":"","Battleback Style":"Dual-Fisheye"}},
{"name":"Mintyy_ParticleSysCore","status":true,"description":"Controls the particle system made via 3D objects.","parameters":{}},
{"name":"====== CONTROLS ========","status":true,"description":"================================================================================","parameters":{}},
{"name":"Mintyy_NCSample","status":true,"description":"A sample ThreeJS Stage Scene you can call. (Developer Tool)","parameters":{}},
{"name":"OrbitControls","status":true,"description":"","parameters":{}},
{"name":"====== EFECTS ========","status":true,"description":"================================================================================","parameters":{}},
{"name":"Mintyy_RealisticWater","status":true,"description":"Creates a Realistic Water using ThreeJS.","parameters":{}},
{"name":"Mintyy_TitleParticleMovement","status":true,"description":"Creates a Particle and Title 3D Movement in the title screen.","parameters":{}},
{"name":"Mintyy_3DBattleBackSprite","status":true,"description":"Battleback : Default, Skybox, Dual-Fisheye, Equirectangular","parameters":{}},
{"name":"Mintyy_3DParallaxSprite","status":true,"description":"Parallax : Default, Skybox, Dual-Fisheye, Equirectangular","parameters":{}},
{"name":"Mintyy_ParticleMouseFollow","status":true,"description":"Controls a following mouse particle. (Dev Tool)","parameters":{}},
{"name":"Mintyy_ParticleZoom","status":true,"description":"Creates a particle scene with zooming experience.","parameters":{}}
];
